port = 8080

[transcode]
video_codec = "libx264"
extra_args = ["-preset", "ultrafast", "-tune", "zerolatency"]
audio_codec = "aac"
audio_bitrate = "128k"
subtitles = true
realtime = true
format = "matroska"

[[quality]]
name = "source"
passthrough = true

[[quality]]
name = "1080p"
bitrate = "8000k"
resolution = "1920x1080"

[[quality]]
name = "720p"
bitrate = "3000k"
resolution = "1280x720"

[[quality]]
name = "480p"
bitrate = "1000k"
resolution = "854x480"

[hls]
enabled = false
segment_duration = 4
auto_generate = false
qualities = ["1080p", "720p", "480p"]
segment_type = "mpegts"
